packages:
  - apps/*
  - packages/*

autoInstallPeers: true

catalog:
  "@types/node": ^22.13.0
  eslint: ^9.29.0
  typescript: ^5.8.3
  "@jest/globals": ^30.0.0
  jest: ^30.0.0
  jest-environment-jsdom: ^30.0.0
  expect: ^30.0.0
  zod: ^3.25.76

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
